@url= http://localhost:3001/api/persons


###
GET http://localhost:3001/info HTTP/1.1

###
GET {{url}}/639c3ce0acfe0203d4c0435c HTTP/1.1

###
GET http://localhost:3001/api/persons HTTP/1.1
Authorization: jikafgew0234

###
DELETE {{url}}/639c40168f539874f2bb2098 HTTP/1.1
Authorization: jikafgew0234

###
POST {{url}} HTTP/1.1
Authorization: jikafgew0234
Content-Type: application/json

{
  "name": "m1q",
  "number": "010-123456",
  "age": 23
}

###
PUT {{url}}/639c3ce0acfe0203d4c0435c HTTP/1.1
Content-Type: application/json

{
  "name": "dd",
  "number": "010-1234567"
}