@url= http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons HTTP/1.1
Authorization: jikafgew0234

###
DELETE http://localhost:3001/api/persons/3 HTTP/1.1
Authorization: jikafgew0234

###
POST {{url}} HTTP/1.1
Authorization: jikafgew0234
Content-Type: application/json

{
  "name": "Jim",
  "number": "010-123456"
}